---
- name: Install apache2-utils for htpasswd
  apt:
    name: apache2-utils
    state: present

- name: Install passlib for htpasswd module
  apt:
    name: python3-passlib
    state: present
    update_cache: yes
  # pip:
  #   name: passlib
  #   executable: pip3

- name: Create htpasswd file for Glances
  community.general.htpasswd:
    path: /etc/nginx/.htpasswd
    name: "{{ nginx_basic_auth_user }}"
    password: "{{ nginx_basic_auth_password }}"
    crypt_scheme: bcrypt
    state: present
  notify: Reload nginx

- name: Ensure /glances location block is secured
  blockinfile:
    path: /etc/nginx/sites-available/default
    marker: "# {mark} ANSIBLE MANAGED GGLANCES BLOCK"
    insertafter: "location /glances/ {"
    block: |
      auth_basic "Restricted Area";
      auth_basic_user_file /etc/nginx/.htpasswd;
  notify: Reload nginx
