---
- name: Allow SSH
  ufw:
    rule: allow
    port: 22

- name: Allow HTTP
  ufw:
    rule: allow
    port: 80

- name: Allow HTTPS
  ufw:
    rule: allow
    port: 443

- name: Allow PostgreSQL
  ufw:
    rule: allow
    port: 5432

- name: Allow Glances Web UI
  ufw:
    rule: allow
    port: 61208

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny
