---
- name: Validate nginx config before reload
  command: nginx -t
  register: nginx_test
  changed_when: false
  failed_when: nginx_test.rc != 0

- name: Reload nginx if config is valid
  systemd:
    name: nginx
    state: reloaded
  when: nginx_test.rc == 0

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
