---
- name: Install tmux
  apt:
    name: tmux
    state: present

- name: Upload default .tmux.conf
  copy:
    src: tmux.conf
    dest: /root/.tmux.conf
    mode: '0644'

- name: Set default shell for tmux to zsh
  lineinfile:
    path: /root/.tmux.conf
    line: "set-option -g default-shell /usr/bin/zsh"
    create: yes

- name: Ensure glances and lazydocker are installed
  apt:
    name:
      - glances
      - python3-pip
    state: present

- name: Check if lazydocker is already installed
  stat:
    path: /usr/local/bin/lazydocker
  register: lazydocker_installed

- name: Install lazydocker if not already installed
  shell: |
    curl -fsSL https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
  args:
    executable: /bin/bash
  when: lazydocker_installed.stat.exists == false
  register: lazydocker_result
  changed_when: "'Lazydocker was successfully installed' in lazydocker_result.stdout"
  tags: lazydocker

# - name: Download lazydocker latest release
#   get_url:
#     url: https://github.com/jesseduffield/lazydocker/releases/latest/download/lazydocker_linux_amd64.tar.gz
#     dest: /tmp/lazydocker.tar.gz

# - name: Extract and install lazydocker
#   unarchive:
#     src: /tmp/lazydocker.tar.gz
#     dest: /usr/local/bin/
#     remote_src: yes
#     mode: '0755'

- name: Create main tmux session with default windows
  shell: |
    tmux has-session -t main || \
    tmux new-session -d -s main -n htop "htop" \; \
         new-window -n glances "glances" \; \
         new-window -n docker "docker stats" \; \
         new-window -n lazydocker "lazydocker" \; \
         new-window -n disk "watch -n 5 df -h"
  args:
    executable: /bin/bash
