---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install base packages
  apt:
    name:
      - git
      - curl
      - wget
      - htop
      - jq
      - net-tools
      - ufw
      - unzip
      - ncdu
      - rsync
      - openssl
      - build-essential
      - python3-dev
      - libffi-dev
      - tree
    state: present

- name: Print system info
  debug:
    msg: |
      Host: {{ inventory_hostname }}
      CPU cores: {{ ansible_processor_cores }}
      RAM: {{ ansible_memtotal_mb | int // 1024 }} GB
      Free disk space (/): {{
        (ansible_mounts | selectattr('mount', 'equalto', '/') | map(attribute='size_available') | first | int / (1024**3)) | round(1)
      }} GB

- import_tasks: preflight_checks.yml
- import_tasks: timezone.yml
